// Git Revision Utility
// This file is automatically generated during Docker build

const GIT_REVISION = process.env.REACT_APP_GIT_REVISION || 'unknown';
const BUILD_TIME = process.env.REACT_APP_BUILD_TIME || new Date().toISOString();

// Helper function to get revision info
const getRevisionInfo = () => ({
  revision: GIT_REVISION,
  buildTime: BUILD_TIME,
  timestamp: new Date().toLocaleString()
});

export { GIT_REVISION, BUILD_TIME, getRevisionInfo };
